version: "3.7"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    volumes:
      - ./ek/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - observability

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx256m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data_obs:/usr/share/elasticsearch/data
    restart: always
    ports:
      - "9200:9200"
    networks:
      - observability
    depends_on:
      - kibana

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.13.0
    container_name: metricbeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./beats/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: always
    networks:
      - observability
    depends_on:
      - kibana

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.13.0
    container_name: heartbeat
    volumes:
      - ./beats/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    restart: always
    environment:
      - setup.kibana.host=kibana:5601
    networks:
      - observability
    depends_on:
      - kibana

  apm:
    image: docker.elastic.co/apm/apm-server-oss:7.13.0
    container_name: apm
    volumes:
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    restart: always
    networks:
      - observability

volumes:
  elastic_data_obs:

networks:
  observability:
    external: true
    driver: bridge
